runtime: python27
api_version: 1
threadsafe: true
service: website-2017

skip_files:
- ^node_modules$
- ^\.idea$

handlers:
- url: /images
  static_dir: public/images
  secure: always

- url: /css
  static_dir: public/css
  secure: always

- url: /fonts
  static_dir: public/fonts
  secure: always

- url: /js
  static_dir: public/js
  secure: always

- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always